/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/traefik/hub-crds/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AIServices returns a AIServiceInformer.
	AIServices() TypedAIServiceInformer
	// APIs returns a APIInformer.
	APIs() TypedAPIInformer
	// APIAuths returns a APIAuthInformer.
	APIAuths() TypedAPIAuthInformer
	// APIBundles returns a APIBundleInformer.
	APIBundles() TypedAPIBundleInformer
	// APICatalogItems returns a APICatalogItemInformer.
	APICatalogItems() TypedAPICatalogItemInformer
	// APIPlans returns a APIPlanInformer.
	APIPlans() TypedAPIPlanInformer
	// APIPortals returns a APIPortalInformer.
	APIPortals() TypedAPIPortalInformer
	// APIPortalAuths returns a APIPortalAuthInformer.
	APIPortalAuths() TypedAPIPortalAuthInformer
	// APIRateLimits returns a APIRateLimitInformer.
	APIRateLimits() TypedAPIRateLimitInformer
	// APIVersions returns a APIVersionInformer.
	APIVersions() TypedAPIVersionInformer
	// AccessControlPolicies returns a AccessControlPolicyInformer.
	AccessControlPolicies() TypedAccessControlPolicyInformer
	// ContentItems returns a ContentItemInformer.
	ContentItems() TypedContentItemInformer
	// ManagedApplications returns a ManagedApplicationInformer.
	ManagedApplications() TypedManagedApplicationInformer
	// ManagedSubscriptions returns a ManagedSubscriptionInformer.
	ManagedSubscriptions() TypedManagedSubscriptionInformer
	// Uplinks returns a UplinkInformer.
	Uplinks() TypedUplinkInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AIServices returns a TypedAIServiceInformer.
func (v *version) AIServices() TypedAIServiceInformer {
	return &aIServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIs returns a TypedAPIInformer.
func (v *version) APIs() TypedAPIInformer {
	return &aPIInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIAuths returns a TypedAPIAuthInformer.
func (v *version) APIAuths() TypedAPIAuthInformer {
	return &aPIAuthInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIBundles returns a TypedAPIBundleInformer.
func (v *version) APIBundles() TypedAPIBundleInformer {
	return &aPIBundleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APICatalogItems returns a TypedAPICatalogItemInformer.
func (v *version) APICatalogItems() TypedAPICatalogItemInformer {
	return &aPICatalogItemInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIPlans returns a TypedAPIPlanInformer.
func (v *version) APIPlans() TypedAPIPlanInformer {
	return &aPIPlanInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIPortals returns a TypedAPIPortalInformer.
func (v *version) APIPortals() TypedAPIPortalInformer {
	return &aPIPortalInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIPortalAuths returns a TypedAPIPortalAuthInformer.
func (v *version) APIPortalAuths() TypedAPIPortalAuthInformer {
	return &aPIPortalAuthInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIRateLimits returns a TypedAPIRateLimitInformer.
func (v *version) APIRateLimits() TypedAPIRateLimitInformer {
	return &aPIRateLimitInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// APIVersions returns a TypedAPIVersionInformer.
func (v *version) APIVersions() TypedAPIVersionInformer {
	return &aPIVersionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AccessControlPolicies returns a TypedAccessControlPolicyInformer.
func (v *version) AccessControlPolicies() TypedAccessControlPolicyInformer {
	return &accessControlPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ContentItems returns a TypedContentItemInformer.
func (v *version) ContentItems() TypedContentItemInformer {
	return &contentItemInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ManagedApplications returns a TypedManagedApplicationInformer.
func (v *version) ManagedApplications() TypedManagedApplicationInformer {
	return &managedApplicationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ManagedSubscriptions returns a TypedManagedSubscriptionInformer.
func (v *version) ManagedSubscriptions() TypedManagedSubscriptionInformer {
	return &managedSubscriptionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Uplinks returns a TypedUplinkInformer.
func (v *version) Uplinks() TypedUplinkInformer {
	return &uplinkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
