/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apishubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	versioned "github.com/traefik/hub-crds/pkg/client/clientset/versioned"
	internalinterfaces "github.com/traefik/hub-crds/pkg/client/informers/externalversions/internalinterfaces"
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/client/listers/hub/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedSubscriptionInformer provides access to a shared informer and lister for
// ManagedSubscriptions. Prefer using the type-safe variant (see [TypedManagedSubscriptionInformer]).
type ManagedSubscriptionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() hubv1alpha1.ManagedSubscriptionLister
}

// TypedManagedSubscriptionInformer provides access to a shared informer and lister for
// ManagedSubscriptions, including the type-safe TypedInformer variant.
// It is a superset of ManagedSubscriptionInformer.
type TypedManagedSubscriptionInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ManagedSubscriptionIndexInformer
	Lister() hubv1alpha1.ManagedSubscriptionLister
}

// ManagedSubscriptionIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ManagedSubscriptionIndexInformer cache.TypedSharedIndexInformer[*apishubv1alpha1.ManagedSubscription]

// ManagedSubscriptionHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for ManagedSubscription.
type ManagedSubscriptionHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apishubv1alpha1.ManagedSubscription]

// ManagedSubscriptionDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for ManagedSubscription.
type ManagedSubscriptionDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apishubv1alpha1.ManagedSubscription]

// ManagedSubscriptionFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for ManagedSubscription.
type ManagedSubscriptionFilteringHandler = cache.TypedFilteringResourceEventHandler[*apishubv1alpha1.ManagedSubscription]

// ManagedSubscriptionIndexers is a specialization of [cache.TypedIndexers] for ManagedSubscription.
type ManagedSubscriptionIndexers = cache.TypedIndexers[*apishubv1alpha1.ManagedSubscription]

// DeletedManagedSubscription is a specialization of [cache.DeletedObject] for ManagedSubscription.
type DeletedManagedSubscription = cache.DeletedObject[*apishubv1alpha1.ManagedSubscription]

type managedSubscriptionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManagedSubscriptionInformer constructs a new informer for ManagedSubscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedManagedSubscriptionInformer]).
func NewManagedSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewManagedSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedManagedSubscriptionInformer constructs a new informer for ManagedSubscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedManagedSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers ManagedSubscriptionIndexers) ManagedSubscriptionIndexInformer {
	return NewTypedManagedSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredManagedSubscriptionInformer constructs a new informer for ManagedSubscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredManagedSubscriptionInformer]).
func NewFilteredManagedSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedManagedSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredManagedSubscriptionInformer constructs a new informer for ManagedSubscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredManagedSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers ManagedSubscriptionIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ManagedSubscriptionIndexInformer {
	return NewTypedManagedSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewManagedSubscriptionInformerWithOptions constructs a new informer for ManagedSubscription type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedManagedSubscriptionInformerWithOptions]).
func NewManagedSubscriptionInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedManagedSubscriptionInformerWithOptions(client, namespace, options)
}

// NewTypedManagedSubscriptionInformerWithOptions constructs a new informer for ManagedSubscription type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedManagedSubscriptionInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) ManagedSubscriptionIndexInformer {
	gvr := schema.GroupVersionResource{Group: "hub.traefik.io", Version: "v1alpha1", Resource: "managedsubscriptions"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apishubv1alpha1.ManagedSubscription](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.HubV1alpha1().ManagedSubscriptions(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.HubV1alpha1().ManagedSubscriptions(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.HubV1alpha1().ManagedSubscriptions(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.HubV1alpha1().ManagedSubscriptions(namespace).Watch(ctx, opts)
			},
		}, client),
		&apishubv1alpha1.ManagedSubscription{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *managedSubscriptionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedManagedSubscriptionInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *managedSubscriptionInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *managedSubscriptionInformer) TypedInformer() ManagedSubscriptionIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apishubv1alpha1.ManagedSubscription](f.factory.InformerFor(&apishubv1alpha1.ManagedSubscription{}, f.defaultInformer))
}

func (f *managedSubscriptionInformer) Lister() hubv1alpha1.ManagedSubscriptionLister {
	return hubv1alpha1.NewManagedSubscriptionLister(f.Informer().GetIndexer())
}

// ToTypedManagedSubscriptionInformer converts an untyped informer into a TypedManagedSubscriptionInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ManagedSubscription. If that is not the case, calling type-safe methods of the returned
// TypedManagedSubscriptionInformer leads to runtime panics. A safer alternative is to pass
// around a TypedManagedSubscriptionInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedManagedSubscriptionInformer(informer ManagedSubscriptionInformer) TypedManagedSubscriptionInformer {
	if informer, ok := informer.(TypedManagedSubscriptionInformer); ok {
		return informer
	}
	return &managedSubscriptionTypedInformerAdapter{informer}
}

type managedSubscriptionTypedInformerAdapter struct {
	ManagedSubscriptionInformer
}

func (a *managedSubscriptionTypedInformerAdapter) TypedInformer() ManagedSubscriptionIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apishubv1alpha1.ManagedSubscription](a.Informer())
}

// ToManagedSubscriptionIndexInformer converts an untyped informer into a ManagedSubscriptionIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ManagedSubscription. If that is not the case, calling type-safe methods of the returned
// ManagedSubscriptionIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ManagedSubscriptionIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToManagedSubscriptionIndexInformer(informer cache.SharedIndexInformer) ManagedSubscriptionIndexInformer {
	if informer, ok := informer.(ManagedSubscriptionIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apishubv1alpha1.ManagedSubscription](informer)
}
