/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// APILister helps list APIs.
// All objects returned here must be treated as read-only.
type APILister interface {
	// List lists all APIs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.API, err error)
	// APIs returns an object that can list and get APIs.
	APIs(namespace string) APINamespaceLister
	APIListerExpansion
}

// aPILister implements the APILister interface.
type aPILister struct {
	listers.ResourceIndexer[*hubv1alpha1.API]
}

// NewAPILister returns a new APILister.
func NewAPILister(indexer cache.Indexer) APILister {
	return &aPILister{listers.New[*hubv1alpha1.API](indexer, hubv1alpha1.Resource("api"))}
}

// APIs returns an object that can list and get APIs.
func (s *aPILister) APIs(namespace string) APINamespaceLister {
	return aPINamespaceLister{listers.NewNamespaced[*hubv1alpha1.API](s.ResourceIndexer, namespace)}
}

// APINamespaceLister helps list and get APIs.
// All objects returned here must be treated as read-only.
type APINamespaceLister interface {
	// List lists all APIs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.API, err error)
	// Get retrieves the API from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hubv1alpha1.API, error)
	APINamespaceListerExpansion
}

// aPINamespaceLister implements the APINamespaceLister
// interface.
type aPINamespaceLister struct {
	listers.ResourceIndexer[*hubv1alpha1.API]
}
