/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// APIAuthLister helps list APIAuths.
// All objects returned here must be treated as read-only.
type APIAuthLister interface {
	// List lists all APIAuths in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APIAuth, err error)
	// APIAuths returns an object that can list and get APIAuths.
	APIAuths(namespace string) APIAuthNamespaceLister
	APIAuthListerExpansion
}

// aPIAuthLister implements the APIAuthLister interface.
type aPIAuthLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APIAuth]
}

// NewAPIAuthLister returns a new APIAuthLister.
func NewAPIAuthLister(indexer cache.Indexer) APIAuthLister {
	return &aPIAuthLister{listers.New[*hubv1alpha1.APIAuth](indexer, hubv1alpha1.Resource("apiauth"))}
}

// APIAuths returns an object that can list and get APIAuths.
func (s *aPIAuthLister) APIAuths(namespace string) APIAuthNamespaceLister {
	return aPIAuthNamespaceLister{listers.NewNamespaced[*hubv1alpha1.APIAuth](s.ResourceIndexer, namespace)}
}

// APIAuthNamespaceLister helps list and get APIAuths.
// All objects returned here must be treated as read-only.
type APIAuthNamespaceLister interface {
	// List lists all APIAuths in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APIAuth, err error)
	// Get retrieves the APIAuth from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hubv1alpha1.APIAuth, error)
	APIAuthNamespaceListerExpansion
}

// aPIAuthNamespaceLister implements the APIAuthNamespaceLister
// interface.
type aPIAuthNamespaceLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APIAuth]
}
