/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// APIBundleLister helps list APIBundles.
// All objects returned here must be treated as read-only.
type APIBundleLister interface {
	// List lists all APIBundles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APIBundle, err error)
	// APIBundles returns an object that can list and get APIBundles.
	APIBundles(namespace string) APIBundleNamespaceLister
	APIBundleListerExpansion
}

// aPIBundleLister implements the APIBundleLister interface.
type aPIBundleLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APIBundle]
}

// NewAPIBundleLister returns a new APIBundleLister.
func NewAPIBundleLister(indexer cache.Indexer) APIBundleLister {
	return &aPIBundleLister{listers.New[*hubv1alpha1.APIBundle](indexer, hubv1alpha1.Resource("apibundle"))}
}

// APIBundles returns an object that can list and get APIBundles.
func (s *aPIBundleLister) APIBundles(namespace string) APIBundleNamespaceLister {
	return aPIBundleNamespaceLister{listers.NewNamespaced[*hubv1alpha1.APIBundle](s.ResourceIndexer, namespace)}
}

// APIBundleNamespaceLister helps list and get APIBundles.
// All objects returned here must be treated as read-only.
type APIBundleNamespaceLister interface {
	// List lists all APIBundles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APIBundle, err error)
	// Get retrieves the APIBundle from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hubv1alpha1.APIBundle, error)
	APIBundleNamespaceListerExpansion
}

// aPIBundleNamespaceLister implements the APIBundleNamespaceLister
// interface.
type aPIBundleNamespaceLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APIBundle]
}
