/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// APICatalogItemLister helps list APICatalogItems.
// All objects returned here must be treated as read-only.
type APICatalogItemLister interface {
	// List lists all APICatalogItems in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APICatalogItem, err error)
	// APICatalogItems returns an object that can list and get APICatalogItems.
	APICatalogItems(namespace string) APICatalogItemNamespaceLister
	APICatalogItemListerExpansion
}

// aPICatalogItemLister implements the APICatalogItemLister interface.
type aPICatalogItemLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APICatalogItem]
}

// NewAPICatalogItemLister returns a new APICatalogItemLister.
func NewAPICatalogItemLister(indexer cache.Indexer) APICatalogItemLister {
	return &aPICatalogItemLister{listers.New[*hubv1alpha1.APICatalogItem](indexer, hubv1alpha1.Resource("apicatalogitem"))}
}

// APICatalogItems returns an object that can list and get APICatalogItems.
func (s *aPICatalogItemLister) APICatalogItems(namespace string) APICatalogItemNamespaceLister {
	return aPICatalogItemNamespaceLister{listers.NewNamespaced[*hubv1alpha1.APICatalogItem](s.ResourceIndexer, namespace)}
}

// APICatalogItemNamespaceLister helps list and get APICatalogItems.
// All objects returned here must be treated as read-only.
type APICatalogItemNamespaceLister interface {
	// List lists all APICatalogItems in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APICatalogItem, err error)
	// Get retrieves the APICatalogItem from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hubv1alpha1.APICatalogItem, error)
	APICatalogItemNamespaceListerExpansion
}

// aPICatalogItemNamespaceLister implements the APICatalogItemNamespaceLister
// interface.
type aPICatalogItemNamespaceLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APICatalogItem]
}
