/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// APIPortalAuthLister helps list APIPortalAuths.
// All objects returned here must be treated as read-only.
type APIPortalAuthLister interface {
	// List lists all APIPortalAuths in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.APIPortalAuth, err error)
	// APIPortalAuths returns an object that can list and get APIPortalAuths.
	APIPortalAuths(namespace string) APIPortalAuthNamespaceLister
	APIPortalAuthListerExpansion
}

// aPIPortalAuthLister implements the APIPortalAuthLister interface.
type aPIPortalAuthLister struct {
	indexer cache.Indexer
}

// NewAPIPortalAuthLister returns a new APIPortalAuthLister.
func NewAPIPortalAuthLister(indexer cache.Indexer) APIPortalAuthLister {
	return &aPIPortalAuthLister{indexer: indexer}
}

// List lists all APIPortalAuths in the indexer.
func (s *aPIPortalAuthLister) List(selector labels.Selector) (ret []*v1alpha1.APIPortalAuth, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.APIPortalAuth))
	})
	return ret, err
}

// APIPortalAuths returns an object that can list and get APIPortalAuths.
func (s *aPIPortalAuthLister) APIPortalAuths(namespace string) APIPortalAuthNamespaceLister {
	return aPIPortalAuthNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// APIPortalAuthNamespaceLister helps list and get APIPortalAuths.
// All objects returned here must be treated as read-only.
type APIPortalAuthNamespaceLister interface {
	// List lists all APIPortalAuths in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.APIPortalAuth, err error)
	// Get retrieves the APIPortalAuth from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.APIPortalAuth, error)
	APIPortalAuthNamespaceListerExpansion
}

// aPIPortalAuthNamespaceLister implements the APIPortalAuthNamespaceLister
// interface.
type aPIPortalAuthNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all APIPortalAuths in the indexer for a given namespace.
func (s aPIPortalAuthNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.APIPortalAuth, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.APIPortalAuth))
	})
	return ret, err
}

// Get retrieves the APIPortalAuth from the indexer for a given namespace and name.
func (s aPIPortalAuthNamespaceLister) Get(name string) (*v1alpha1.APIPortalAuth, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("apiportalauth"), name)
	}
	return obj.(*v1alpha1.APIPortalAuth), nil
}
