/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// APIRateLimitLister helps list APIRateLimits.
// All objects returned here must be treated as read-only.
type APIRateLimitLister interface {
	// List lists all APIRateLimits in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.APIRateLimit, err error)
	// APIRateLimits returns an object that can list and get APIRateLimits.
	APIRateLimits(namespace string) APIRateLimitNamespaceLister
	APIRateLimitListerExpansion
}

// aPIRateLimitLister implements the APIRateLimitLister interface.
type aPIRateLimitLister struct {
	indexer cache.Indexer
}

// NewAPIRateLimitLister returns a new APIRateLimitLister.
func NewAPIRateLimitLister(indexer cache.Indexer) APIRateLimitLister {
	return &aPIRateLimitLister{indexer: indexer}
}

// List lists all APIRateLimits in the indexer.
func (s *aPIRateLimitLister) List(selector labels.Selector) (ret []*v1alpha1.APIRateLimit, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.APIRateLimit))
	})
	return ret, err
}

// APIRateLimits returns an object that can list and get APIRateLimits.
func (s *aPIRateLimitLister) APIRateLimits(namespace string) APIRateLimitNamespaceLister {
	return aPIRateLimitNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// APIRateLimitNamespaceLister helps list and get APIRateLimits.
// All objects returned here must be treated as read-only.
type APIRateLimitNamespaceLister interface {
	// List lists all APIRateLimits in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.APIRateLimit, err error)
	// Get retrieves the APIRateLimit from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.APIRateLimit, error)
	APIRateLimitNamespaceListerExpansion
}

// aPIRateLimitNamespaceLister implements the APIRateLimitNamespaceLister
// interface.
type aPIRateLimitNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all APIRateLimits in the indexer for a given namespace.
func (s aPIRateLimitNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.APIRateLimit, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.APIRateLimit))
	})
	return ret, err
}

// Get retrieves the APIRateLimit from the indexer for a given namespace and name.
func (s aPIRateLimitNamespaceLister) Get(name string) (*v1alpha1.APIRateLimit, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("apiratelimit"), name)
	}
	return obj.(*v1alpha1.APIRateLimit), nil
}
