/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// APIVersionLister helps list APIVersions.
// All objects returned here must be treated as read-only.
type APIVersionLister interface {
	// List lists all APIVersions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APIVersion, err error)
	// APIVersions returns an object that can list and get APIVersions.
	APIVersions(namespace string) APIVersionNamespaceLister
	APIVersionListerExpansion
}

// aPIVersionLister implements the APIVersionLister interface.
type aPIVersionLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APIVersion]
}

// NewAPIVersionLister returns a new APIVersionLister.
func NewAPIVersionLister(indexer cache.Indexer) APIVersionLister {
	return &aPIVersionLister{listers.New[*hubv1alpha1.APIVersion](indexer, hubv1alpha1.Resource("apiversion"))}
}

// APIVersions returns an object that can list and get APIVersions.
func (s *aPIVersionLister) APIVersions(namespace string) APIVersionNamespaceLister {
	return aPIVersionNamespaceLister{listers.NewNamespaced[*hubv1alpha1.APIVersion](s.ResourceIndexer, namespace)}
}

// APIVersionNamespaceLister helps list and get APIVersions.
// All objects returned here must be treated as read-only.
type APIVersionNamespaceLister interface {
	// List lists all APIVersions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hubv1alpha1.APIVersion, err error)
	// Get retrieves the APIVersion from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hubv1alpha1.APIVersion, error)
	APIVersionNamespaceListerExpansion
}

// aPIVersionNamespaceLister implements the APIVersionNamespaceLister
// interface.
type aPIVersionNamespaceLister struct {
	listers.ResourceIndexer[*hubv1alpha1.APIVersion]
}
