/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ContentItemLister helps list ContentItems.
// All objects returned here must be treated as read-only.
type ContentItemLister interface {
	// List lists all ContentItems in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ContentItem, err error)
	// ContentItems returns an object that can list and get ContentItems.
	ContentItems(namespace string) ContentItemNamespaceLister
	ContentItemListerExpansion
}

// contentItemLister implements the ContentItemLister interface.
type contentItemLister struct {
	indexer cache.Indexer
}

// NewContentItemLister returns a new ContentItemLister.
func NewContentItemLister(indexer cache.Indexer) ContentItemLister {
	return &contentItemLister{indexer: indexer}
}

// List lists all ContentItems in the indexer.
func (s *contentItemLister) List(selector labels.Selector) (ret []*v1alpha1.ContentItem, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ContentItem))
	})
	return ret, err
}

// ContentItems returns an object that can list and get ContentItems.
func (s *contentItemLister) ContentItems(namespace string) ContentItemNamespaceLister {
	return contentItemNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ContentItemNamespaceLister helps list and get ContentItems.
// All objects returned here must be treated as read-only.
type ContentItemNamespaceLister interface {
	// List lists all ContentItems in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ContentItem, err error)
	// Get retrieves the ContentItem from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ContentItem, error)
	ContentItemNamespaceListerExpansion
}

// contentItemNamespaceLister implements the ContentItemNamespaceLister
// interface.
type contentItemNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ContentItems in the indexer for a given namespace.
func (s contentItemNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ContentItem, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ContentItem))
	})
	return ret, err
}

// Get retrieves the ContentItem from the indexer for a given namespace and name.
func (s contentItemNamespaceLister) Get(name string) (*v1alpha1.ContentItem, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("contentitem"), name)
	}
	return obj.(*v1alpha1.ContentItem), nil
}
