/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2024 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// APIListerExpansion allows custom methods to be added to
// APILister.
type APIListerExpansion interface{}

// APINamespaceListerExpansion allows custom methods to be added to
// APINamespaceLister.
type APINamespaceListerExpansion interface{}

// APIAccessListerExpansion allows custom methods to be added to
// APIAccessLister.
type APIAccessListerExpansion interface{}

// APIAccessNamespaceListerExpansion allows custom methods to be added to
// APIAccessNamespaceLister.
type APIAccessNamespaceListerExpansion interface{}

// APIPlanListerExpansion allows custom methods to be added to
// APIPlanLister.
type APIPlanListerExpansion interface{}

// APIPlanNamespaceListerExpansion allows custom methods to be added to
// APIPlanNamespaceLister.
type APIPlanNamespaceListerExpansion interface{}

// APIPortalListerExpansion allows custom methods to be added to
// APIPortalLister.
type APIPortalListerExpansion interface{}

// APIPortalNamespaceListerExpansion allows custom methods to be added to
// APIPortalNamespaceLister.
type APIPortalNamespaceListerExpansion interface{}

// APIRateLimitListerExpansion allows custom methods to be added to
// APIRateLimitLister.
type APIRateLimitListerExpansion interface{}

// APIRateLimitNamespaceListerExpansion allows custom methods to be added to
// APIRateLimitNamespaceLister.
type APIRateLimitNamespaceListerExpansion interface{}

// APIVersionListerExpansion allows custom methods to be added to
// APIVersionLister.
type APIVersionListerExpansion interface{}

// APIVersionNamespaceListerExpansion allows custom methods to be added to
// APIVersionNamespaceLister.
type APIVersionNamespaceListerExpansion interface{}

// AccessControlPolicyListerExpansion allows custom methods to be added to
// AccessControlPolicyLister.
type AccessControlPolicyListerExpansion interface{}
