/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2025 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ManagedApplicationLister helps list ManagedApplications.
// All objects returned here must be treated as read-only.
type ManagedApplicationLister interface {
	// List lists all ManagedApplications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ManagedApplication, err error)
	// ManagedApplications returns an object that can list and get ManagedApplications.
	ManagedApplications(namespace string) ManagedApplicationNamespaceLister
	ManagedApplicationListerExpansion
}

// managedApplicationLister implements the ManagedApplicationLister interface.
type managedApplicationLister struct {
	indexer cache.Indexer
}

// NewManagedApplicationLister returns a new ManagedApplicationLister.
func NewManagedApplicationLister(indexer cache.Indexer) ManagedApplicationLister {
	return &managedApplicationLister{indexer: indexer}
}

// List lists all ManagedApplications in the indexer.
func (s *managedApplicationLister) List(selector labels.Selector) (ret []*v1alpha1.ManagedApplication, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ManagedApplication))
	})
	return ret, err
}

// ManagedApplications returns an object that can list and get ManagedApplications.
func (s *managedApplicationLister) ManagedApplications(namespace string) ManagedApplicationNamespaceLister {
	return managedApplicationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ManagedApplicationNamespaceLister helps list and get ManagedApplications.
// All objects returned here must be treated as read-only.
type ManagedApplicationNamespaceLister interface {
	// List lists all ManagedApplications in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ManagedApplication, err error)
	// Get retrieves the ManagedApplication from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ManagedApplication, error)
	ManagedApplicationNamespaceListerExpansion
}

// managedApplicationNamespaceLister implements the ManagedApplicationNamespaceLister
// interface.
type managedApplicationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ManagedApplications in the indexer for a given namespace.
func (s managedApplicationNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ManagedApplication, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ManagedApplication))
	})
	return ret, err
}

// Get retrieves the ManagedApplication from the indexer for a given namespace and name.
func (s managedApplicationNamespaceLister) Get(name string) (*v1alpha1.ManagedApplication, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("managedapplication"), name)
	}
	return obj.(*v1alpha1.ManagedApplication), nil
}
