/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2024 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ManagedSubscriptionLister helps list ManagedSubscriptions.
// All objects returned here must be treated as read-only.
type ManagedSubscriptionLister interface {
	// List lists all ManagedSubscriptions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ManagedSubscription, err error)
	// ManagedSubscriptions returns an object that can list and get ManagedSubscriptions.
	ManagedSubscriptions(namespace string) ManagedSubscriptionNamespaceLister
	ManagedSubscriptionListerExpansion
}

// managedSubscriptionLister implements the ManagedSubscriptionLister interface.
type managedSubscriptionLister struct {
	indexer cache.Indexer
}

// NewManagedSubscriptionLister returns a new ManagedSubscriptionLister.
func NewManagedSubscriptionLister(indexer cache.Indexer) ManagedSubscriptionLister {
	return &managedSubscriptionLister{indexer: indexer}
}

// List lists all ManagedSubscriptions in the indexer.
func (s *managedSubscriptionLister) List(selector labels.Selector) (ret []*v1alpha1.ManagedSubscription, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ManagedSubscription))
	})
	return ret, err
}

// ManagedSubscriptions returns an object that can list and get ManagedSubscriptions.
func (s *managedSubscriptionLister) ManagedSubscriptions(namespace string) ManagedSubscriptionNamespaceLister {
	return managedSubscriptionNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ManagedSubscriptionNamespaceLister helps list and get ManagedSubscriptions.
// All objects returned here must be treated as read-only.
type ManagedSubscriptionNamespaceLister interface {
	// List lists all ManagedSubscriptions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ManagedSubscription, err error)
	// Get retrieves the ManagedSubscription from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ManagedSubscription, error)
	ManagedSubscriptionNamespaceListerExpansion
}

// managedSubscriptionNamespaceLister implements the ManagedSubscriptionNamespaceLister
// interface.
type managedSubscriptionNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ManagedSubscriptions in the indexer for a given namespace.
func (s managedSubscriptionNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ManagedSubscription, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ManagedSubscription))
	})
	return ret, err
}

// Get retrieves the ManagedSubscription from the indexer for a given namespace and name.
func (s managedSubscriptionNamespaceLister) Get(name string) (*v1alpha1.ManagedSubscription, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("managedsubscription"), name)
	}
	return obj.(*v1alpha1.ManagedSubscription), nil
}
