/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// UplinkLister helps list Uplinks.
// All objects returned here must be treated as read-only.
type UplinkLister interface {
	// List lists all Uplinks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Uplink, err error)
	// Uplinks returns an object that can list and get Uplinks.
	Uplinks(namespace string) UplinkNamespaceLister
	UplinkListerExpansion
}

// uplinkLister implements the UplinkLister interface.
type uplinkLister struct {
	indexer cache.Indexer
}

// NewUplinkLister returns a new UplinkLister.
func NewUplinkLister(indexer cache.Indexer) UplinkLister {
	return &uplinkLister{indexer: indexer}
}

// List lists all Uplinks in the indexer.
func (s *uplinkLister) List(selector labels.Selector) (ret []*v1alpha1.Uplink, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Uplink))
	})
	return ret, err
}

// Uplinks returns an object that can list and get Uplinks.
func (s *uplinkLister) Uplinks(namespace string) UplinkNamespaceLister {
	return uplinkNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// UplinkNamespaceLister helps list and get Uplinks.
// All objects returned here must be treated as read-only.
type UplinkNamespaceLister interface {
	// List lists all Uplinks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Uplink, err error)
	// Get retrieves the Uplink from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Uplink, error)
	UplinkNamespaceListerExpansion
}

// uplinkNamespaceLister implements the UplinkNamespaceLister
// interface.
type uplinkNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Uplinks in the indexer for a given namespace.
func (s uplinkNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.Uplink, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Uplink))
	})
	return ret, err
}

// Get retrieves the Uplink from the indexer for a given namespace and name.
func (s uplinkNamespaceLister) Get(name string) (*v1alpha1.Uplink, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("uplink"), name)
	}
	return obj.(*v1alpha1.Uplink), nil
}
