/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/client/clientset/versioned/typed/hub/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeContentItems implements ContentItemInterface
type fakeContentItems struct {
	*gentype.FakeClientWithList[*v1alpha1.ContentItem, *v1alpha1.ContentItemList]
	Fake *FakeHubV1alpha1
}

func newFakeContentItems(fake *FakeHubV1alpha1, namespace string) hubv1alpha1.ContentItemInterface {
	return &fakeContentItems{
		gentype.NewFakeClientWithList[*v1alpha1.ContentItem, *v1alpha1.ContentItemList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("contentitems"),
			v1alpha1.SchemeGroupVersion.WithKind("ContentItem"),
			func() *v1alpha1.ContentItem { return &v1alpha1.ContentItem{} },
			func() *v1alpha1.ContentItemList { return &v1alpha1.ContentItemList{} },
			func(dst, src *v1alpha1.ContentItemList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ContentItemList) []*v1alpha1.ContentItem {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ContentItemList, items []*v1alpha1.ContentItem) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
