/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2024 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAPICollections implements APICollectionInterface
type FakeAPICollections struct {
	Fake *FakeHubV1alpha1
}

var apicollectionsResource = v1alpha1.SchemeGroupVersion.WithResource("apicollections")

var apicollectionsKind = v1alpha1.SchemeGroupVersion.WithKind("APICollection")

// Get takes name of the aPICollection, and returns the corresponding aPICollection object, and an error if there is any.
func (c *FakeAPICollections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APICollection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(apicollectionsResource, name), &v1alpha1.APICollection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APICollection), err
}

// List takes label and field selectors, and returns the list of APICollections that match those selectors.
func (c *FakeAPICollections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APICollectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(apicollectionsResource, apicollectionsKind, opts), &v1alpha1.APICollectionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.APICollectionList{ListMeta: obj.(*v1alpha1.APICollectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.APICollectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aPICollections.
func (c *FakeAPICollections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(apicollectionsResource, opts))
}

// Create takes the representation of a aPICollection and creates it.  Returns the server's representation of the aPICollection, and an error, if there is any.
func (c *FakeAPICollections) Create(ctx context.Context, aPICollection *v1alpha1.APICollection, opts v1.CreateOptions) (result *v1alpha1.APICollection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(apicollectionsResource, aPICollection), &v1alpha1.APICollection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APICollection), err
}

// Update takes the representation of a aPICollection and updates it. Returns the server's representation of the aPICollection, and an error, if there is any.
func (c *FakeAPICollections) Update(ctx context.Context, aPICollection *v1alpha1.APICollection, opts v1.UpdateOptions) (result *v1alpha1.APICollection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(apicollectionsResource, aPICollection), &v1alpha1.APICollection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APICollection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAPICollections) UpdateStatus(ctx context.Context, aPICollection *v1alpha1.APICollection, opts v1.UpdateOptions) (*v1alpha1.APICollection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(apicollectionsResource, "status", aPICollection), &v1alpha1.APICollection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APICollection), err
}

// Delete takes name of the aPICollection and deletes it. Returns an error if one occurs.
func (c *FakeAPICollections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(apicollectionsResource, name, opts), &v1alpha1.APICollection{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAPICollections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(apicollectionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.APICollectionList{})
	return err
}

// Patch applies the patch and returns the patched aPICollection.
func (c *FakeAPICollections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APICollection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(apicollectionsResource, name, pt, data, subresources...), &v1alpha1.APICollection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APICollection), err
}
