/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/client/clientset/versioned/typed/hub/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeUplinks implements UplinkInterface
type fakeUplinks struct {
	*gentype.FakeClientWithList[*v1alpha1.Uplink, *v1alpha1.UplinkList]
	Fake *FakeHubV1alpha1
}

func newFakeUplinks(fake *FakeHubV1alpha1, namespace string) hubv1alpha1.UplinkInterface {
	return &fakeUplinks{
		gentype.NewFakeClientWithList[*v1alpha1.Uplink, *v1alpha1.UplinkList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("uplinks"),
			v1alpha1.SchemeGroupVersion.WithKind("Uplink"),
			func() *v1alpha1.Uplink { return &v1alpha1.Uplink{} },
			func() *v1alpha1.UplinkList { return &v1alpha1.UplinkList{} },
			func(dst, src *v1alpha1.UplinkList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.UplinkList) []*v1alpha1.Uplink { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.UplinkList, items []*v1alpha1.Uplink) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
