/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2025 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAPIPortalAuths implements APIPortalAuthInterface
type FakeAPIPortalAuths struct {
	Fake *FakeHubV1alpha1
	ns   string
}

var apiportalauthsResource = v1alpha1.SchemeGroupVersion.WithResource("apiportalauths")

var apiportalauthsKind = v1alpha1.SchemeGroupVersion.WithKind("APIPortalAuth")

// Get takes name of the aPIPortalAuth, and returns the corresponding aPIPortalAuth object, and an error if there is any.
func (c *FakeAPIPortalAuths) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIPortalAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apiportalauthsResource, c.ns, name), &v1alpha1.APIPortalAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIPortalAuth), err
}

// List takes label and field selectors, and returns the list of APIPortalAuths that match those selectors.
func (c *FakeAPIPortalAuths) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APIPortalAuthList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apiportalauthsResource, apiportalauthsKind, c.ns, opts), &v1alpha1.APIPortalAuthList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.APIPortalAuthList{ListMeta: obj.(*v1alpha1.APIPortalAuthList).ListMeta}
	for _, item := range obj.(*v1alpha1.APIPortalAuthList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aPIPortalAuths.
func (c *FakeAPIPortalAuths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apiportalauthsResource, c.ns, opts))

}

// Create takes the representation of a aPIPortalAuth and creates it.  Returns the server's representation of the aPIPortalAuth, and an error, if there is any.
func (c *FakeAPIPortalAuths) Create(ctx context.Context, aPIPortalAuth *v1alpha1.APIPortalAuth, opts v1.CreateOptions) (result *v1alpha1.APIPortalAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apiportalauthsResource, c.ns, aPIPortalAuth), &v1alpha1.APIPortalAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIPortalAuth), err
}

// Update takes the representation of a aPIPortalAuth and updates it. Returns the server's representation of the aPIPortalAuth, and an error, if there is any.
func (c *FakeAPIPortalAuths) Update(ctx context.Context, aPIPortalAuth *v1alpha1.APIPortalAuth, opts v1.UpdateOptions) (result *v1alpha1.APIPortalAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apiportalauthsResource, c.ns, aPIPortalAuth), &v1alpha1.APIPortalAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIPortalAuth), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAPIPortalAuths) UpdateStatus(ctx context.Context, aPIPortalAuth *v1alpha1.APIPortalAuth, opts v1.UpdateOptions) (*v1alpha1.APIPortalAuth, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apiportalauthsResource, "status", c.ns, aPIPortalAuth), &v1alpha1.APIPortalAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIPortalAuth), err
}

// Delete takes name of the aPIPortalAuth and deletes it. Returns an error if one occurs.
func (c *FakeAPIPortalAuths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(apiportalauthsResource, c.ns, name, opts), &v1alpha1.APIPortalAuth{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAPIPortalAuths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apiportalauthsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.APIPortalAuthList{})
	return err
}

// Patch applies the patch and returns the patched aPIPortalAuth.
func (c *FakeAPIPortalAuths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIPortalAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apiportalauthsResource, c.ns, name, pt, data, subresources...), &v1alpha1.APIPortalAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIPortalAuth), err
}
