/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/client/clientset/versioned/typed/hub/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeHubV1alpha1 struct {
	*testing.Fake
}

func (c *FakeHubV1alpha1) AIServices(namespace string) v1alpha1.AIServiceInterface {
	return &FakeAIServices{c, namespace}
}

func (c *FakeHubV1alpha1) APIs(namespace string) v1alpha1.APIInterface {
	return &FakeAPIs{c, namespace}
}

func (c *FakeHubV1alpha1) APIAuths(namespace string) v1alpha1.APIAuthInterface {
	return &FakeAPIAuths{c, namespace}
}

func (c *FakeHubV1alpha1) APIBundles(namespace string) v1alpha1.APIBundleInterface {
	return &FakeAPIBundles{c, namespace}
}

func (c *FakeHubV1alpha1) APICatalogItems(namespace string) v1alpha1.APICatalogItemInterface {
	return &FakeAPICatalogItems{c, namespace}
}

func (c *FakeHubV1alpha1) APIPlans(namespace string) v1alpha1.APIPlanInterface {
	return &FakeAPIPlans{c, namespace}
}

func (c *FakeHubV1alpha1) APIPortals(namespace string) v1alpha1.APIPortalInterface {
	return &FakeAPIPortals{c, namespace}
}

func (c *FakeHubV1alpha1) APIPortalAuths(namespace string) v1alpha1.APIPortalAuthInterface {
	return &FakeAPIPortalAuths{c, namespace}
}

func (c *FakeHubV1alpha1) APIRateLimits(namespace string) v1alpha1.APIRateLimitInterface {
	return &FakeAPIRateLimits{c, namespace}
}

func (c *FakeHubV1alpha1) APIVersions(namespace string) v1alpha1.APIVersionInterface {
	return &FakeAPIVersions{c, namespace}
}

func (c *FakeHubV1alpha1) AccessControlPolicies() v1alpha1.AccessControlPolicyInterface {
	return &FakeAccessControlPolicies{c}
}

func (c *FakeHubV1alpha1) ManagedApplications(namespace string) v1alpha1.ManagedApplicationInterface {
	return &FakeManagedApplications{c, namespace}
}

func (c *FakeHubV1alpha1) ManagedSubscriptions(namespace string) v1alpha1.ManagedSubscriptionInterface {
	return &FakeManagedSubscriptions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeHubV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
