/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/client/clientset/versioned/typed/hub/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAPICatalogItems implements APICatalogItemInterface
type fakeAPICatalogItems struct {
	*gentype.FakeClientWithList[*v1alpha1.APICatalogItem, *v1alpha1.APICatalogItemList]
	Fake *FakeHubV1alpha1
}

func newFakeAPICatalogItems(fake *FakeHubV1alpha1, namespace string) hubv1alpha1.APICatalogItemInterface {
	return &fakeAPICatalogItems{
		gentype.NewFakeClientWithList[*v1alpha1.APICatalogItem, *v1alpha1.APICatalogItemList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("apicatalogitems"),
			v1alpha1.SchemeGroupVersion.WithKind("APICatalogItem"),
			func() *v1alpha1.APICatalogItem { return &v1alpha1.APICatalogItem{} },
			func() *v1alpha1.APICatalogItemList { return &v1alpha1.APICatalogItemList{} },
			func(dst, src *v1alpha1.APICatalogItemList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.APICatalogItemList) []*v1alpha1.APICatalogItem {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.APICatalogItemList, items []*v1alpha1.APICatalogItem) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
