/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	hubv1alpha1 "github.com/traefik/hub-crds/pkg/client/clientset/versioned/typed/hub/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAPIPortalAuths implements APIPortalAuthInterface
type fakeAPIPortalAuths struct {
	*gentype.FakeClientWithList[*v1alpha1.APIPortalAuth, *v1alpha1.APIPortalAuthList]
	Fake *FakeHubV1alpha1
}

func newFakeAPIPortalAuths(fake *FakeHubV1alpha1, namespace string) hubv1alpha1.APIPortalAuthInterface {
	return &fakeAPIPortalAuths{
		gentype.NewFakeClientWithList[*v1alpha1.APIPortalAuth, *v1alpha1.APIPortalAuthList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("apiportalauths"),
			v1alpha1.SchemeGroupVersion.WithKind("APIPortalAuth"),
			func() *v1alpha1.APIPortalAuth { return &v1alpha1.APIPortalAuth{} },
			func() *v1alpha1.APIPortalAuthList { return &v1alpha1.APIPortalAuthList{} },
			func(dst, src *v1alpha1.APIPortalAuthList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.APIPortalAuthList) []*v1alpha1.APIPortalAuth {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.APIPortalAuthList, items []*v1alpha1.APIPortalAuth) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
