/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2025 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	scheme "github.com/traefik/hub-crds/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AccessControlPoliciesGetter has a method to return a AccessControlPolicyInterface.
// A group's client should implement this interface.
type AccessControlPoliciesGetter interface {
	AccessControlPolicies() AccessControlPolicyInterface
}

// AccessControlPolicyInterface has methods to work with AccessControlPolicy resources.
type AccessControlPolicyInterface interface {
	Create(ctx context.Context, accessControlPolicy *v1alpha1.AccessControlPolicy, opts v1.CreateOptions) (*v1alpha1.AccessControlPolicy, error)
	Update(ctx context.Context, accessControlPolicy *v1alpha1.AccessControlPolicy, opts v1.UpdateOptions) (*v1alpha1.AccessControlPolicy, error)
	UpdateStatus(ctx context.Context, accessControlPolicy *v1alpha1.AccessControlPolicy, opts v1.UpdateOptions) (*v1alpha1.AccessControlPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AccessControlPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AccessControlPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccessControlPolicy, err error)
	AccessControlPolicyExpansion
}

// accessControlPolicies implements AccessControlPolicyInterface
type accessControlPolicies struct {
	client rest.Interface
}

// newAccessControlPolicies returns a AccessControlPolicies
func newAccessControlPolicies(c *HubV1alpha1Client) *accessControlPolicies {
	return &accessControlPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the accessControlPolicy, and returns the corresponding accessControlPolicy object, and an error if there is any.
func (c *accessControlPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AccessControlPolicy, err error) {
	result = &v1alpha1.AccessControlPolicy{}
	err = c.client.Get().
		Resource("accesscontrolpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AccessControlPolicies that match those selectors.
func (c *accessControlPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AccessControlPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AccessControlPolicyList{}
	err = c.client.Get().
		Resource("accesscontrolpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested accessControlPolicies.
func (c *accessControlPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("accesscontrolpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a accessControlPolicy and creates it.  Returns the server's representation of the accessControlPolicy, and an error, if there is any.
func (c *accessControlPolicies) Create(ctx context.Context, accessControlPolicy *v1alpha1.AccessControlPolicy, opts v1.CreateOptions) (result *v1alpha1.AccessControlPolicy, err error) {
	result = &v1alpha1.AccessControlPolicy{}
	err = c.client.Post().
		Resource("accesscontrolpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accessControlPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a accessControlPolicy and updates it. Returns the server's representation of the accessControlPolicy, and an error, if there is any.
func (c *accessControlPolicies) Update(ctx context.Context, accessControlPolicy *v1alpha1.AccessControlPolicy, opts v1.UpdateOptions) (result *v1alpha1.AccessControlPolicy, err error) {
	result = &v1alpha1.AccessControlPolicy{}
	err = c.client.Put().
		Resource("accesscontrolpolicies").
		Name(accessControlPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accessControlPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *accessControlPolicies) UpdateStatus(ctx context.Context, accessControlPolicy *v1alpha1.AccessControlPolicy, opts v1.UpdateOptions) (result *v1alpha1.AccessControlPolicy, err error) {
	result = &v1alpha1.AccessControlPolicy{}
	err = c.client.Put().
		Resource("accesscontrolpolicies").
		Name(accessControlPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accessControlPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the accessControlPolicy and deletes it. Returns an error if one occurs.
func (c *accessControlPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("accesscontrolpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *accessControlPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("accesscontrolpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched accessControlPolicy.
func (c *accessControlPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccessControlPolicy, err error) {
	result = &v1alpha1.AccessControlPolicy{}
	err = c.client.Patch(pt).
		Resource("accesscontrolpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
