/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2025 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	scheme "github.com/traefik/hub-crds/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// APIPlansGetter has a method to return a APIPlanInterface.
// A group's client should implement this interface.
type APIPlansGetter interface {
	APIPlans(namespace string) APIPlanInterface
}

// APIPlanInterface has methods to work with APIPlan resources.
type APIPlanInterface interface {
	Create(ctx context.Context, aPIPlan *v1alpha1.APIPlan, opts v1.CreateOptions) (*v1alpha1.APIPlan, error)
	Update(ctx context.Context, aPIPlan *v1alpha1.APIPlan, opts v1.UpdateOptions) (*v1alpha1.APIPlan, error)
	UpdateStatus(ctx context.Context, aPIPlan *v1alpha1.APIPlan, opts v1.UpdateOptions) (*v1alpha1.APIPlan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.APIPlan, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.APIPlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIPlan, err error)
	APIPlanExpansion
}

// aPIPlans implements APIPlanInterface
type aPIPlans struct {
	client rest.Interface
	ns     string
}

// newAPIPlans returns a APIPlans
func newAPIPlans(c *HubV1alpha1Client, namespace string) *aPIPlans {
	return &aPIPlans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aPIPlan, and returns the corresponding aPIPlan object, and an error if there is any.
func (c *aPIPlans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIPlan, err error) {
	result = &v1alpha1.APIPlan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apiplans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of APIPlans that match those selectors.
func (c *aPIPlans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APIPlanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.APIPlanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apiplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aPIPlans.
func (c *aPIPlans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("apiplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aPIPlan and creates it.  Returns the server's representation of the aPIPlan, and an error, if there is any.
func (c *aPIPlans) Create(ctx context.Context, aPIPlan *v1alpha1.APIPlan, opts v1.CreateOptions) (result *v1alpha1.APIPlan, err error) {
	result = &v1alpha1.APIPlan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("apiplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIPlan).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aPIPlan and updates it. Returns the server's representation of the aPIPlan, and an error, if there is any.
func (c *aPIPlans) Update(ctx context.Context, aPIPlan *v1alpha1.APIPlan, opts v1.UpdateOptions) (result *v1alpha1.APIPlan, err error) {
	result = &v1alpha1.APIPlan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apiplans").
		Name(aPIPlan.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIPlan).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aPIPlans) UpdateStatus(ctx context.Context, aPIPlan *v1alpha1.APIPlan, opts v1.UpdateOptions) (result *v1alpha1.APIPlan, err error) {
	result = &v1alpha1.APIPlan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apiplans").
		Name(aPIPlan.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIPlan).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aPIPlan and deletes it. Returns an error if one occurs.
func (c *aPIPlans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apiplans").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aPIPlans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apiplans").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aPIPlan.
func (c *aPIPlans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIPlan, err error) {
	result = &v1alpha1.APIPlan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("apiplans").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
