/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	hubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	scheme "github.com/traefik/hub-crds/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// APIPortalAuthsGetter has a method to return a APIPortalAuthInterface.
// A group's client should implement this interface.
type APIPortalAuthsGetter interface {
	APIPortalAuths(namespace string) APIPortalAuthInterface
}

// APIPortalAuthInterface has methods to work with APIPortalAuth resources.
type APIPortalAuthInterface interface {
	Create(ctx context.Context, aPIPortalAuth *hubv1alpha1.APIPortalAuth, opts v1.CreateOptions) (*hubv1alpha1.APIPortalAuth, error)
	Update(ctx context.Context, aPIPortalAuth *hubv1alpha1.APIPortalAuth, opts v1.UpdateOptions) (*hubv1alpha1.APIPortalAuth, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aPIPortalAuth *hubv1alpha1.APIPortalAuth, opts v1.UpdateOptions) (*hubv1alpha1.APIPortalAuth, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*hubv1alpha1.APIPortalAuth, error)
	List(ctx context.Context, opts v1.ListOptions) (*hubv1alpha1.APIPortalAuthList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hubv1alpha1.APIPortalAuth, err error)
	APIPortalAuthExpansion
}

// aPIPortalAuths implements APIPortalAuthInterface
type aPIPortalAuths struct {
	*gentype.ClientWithList[*hubv1alpha1.APIPortalAuth, *hubv1alpha1.APIPortalAuthList]
}

// newAPIPortalAuths returns a APIPortalAuths
func newAPIPortalAuths(c *HubV1alpha1Client, namespace string) *aPIPortalAuths {
	return &aPIPortalAuths{
		gentype.NewClientWithList[*hubv1alpha1.APIPortalAuth, *hubv1alpha1.APIPortalAuthList](
			"apiportalauths",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *hubv1alpha1.APIPortalAuth { return &hubv1alpha1.APIPortalAuth{} },
			func() *hubv1alpha1.APIPortalAuthList { return &hubv1alpha1.APIPortalAuthList{} },
		),
	}
}
