/*
The GNU AFFERO GENERAL PUBLIC LICENSE

Copyright (c) 2020-2026 Traefik Labs

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	hubv1alpha1 "github.com/traefik/hub-crds/pkg/apis/hub/v1alpha1"
	scheme "github.com/traefik/hub-crds/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// UplinksGetter has a method to return a UplinkInterface.
// A group's client should implement this interface.
type UplinksGetter interface {
	Uplinks(namespace string) UplinkInterface
}

// UplinkInterface has methods to work with Uplink resources.
type UplinkInterface interface {
	Create(ctx context.Context, uplink *hubv1alpha1.Uplink, opts v1.CreateOptions) (*hubv1alpha1.Uplink, error)
	Update(ctx context.Context, uplink *hubv1alpha1.Uplink, opts v1.UpdateOptions) (*hubv1alpha1.Uplink, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, uplink *hubv1alpha1.Uplink, opts v1.UpdateOptions) (*hubv1alpha1.Uplink, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*hubv1alpha1.Uplink, error)
	List(ctx context.Context, opts v1.ListOptions) (*hubv1alpha1.UplinkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hubv1alpha1.Uplink, err error)
	UplinkExpansion
}

// uplinks implements UplinkInterface
type uplinks struct {
	*gentype.ClientWithList[*hubv1alpha1.Uplink, *hubv1alpha1.UplinkList]
}

// newUplinks returns a Uplinks
func newUplinks(c *HubV1alpha1Client, namespace string) *uplinks {
	return &uplinks{
		gentype.NewClientWithList[*hubv1alpha1.Uplink, *hubv1alpha1.UplinkList](
			"uplinks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *hubv1alpha1.Uplink { return &hubv1alpha1.Uplink{} },
			func() *hubv1alpha1.UplinkList { return &hubv1alpha1.UplinkList{} },
		),
	}
}
